repos:
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
        - id: check-ast
        - id: detect-private-key
    - repo: local
      hooks:
#        - id: pylint
#          name: pylint
#          entry: pylint
#          language: system
#          types: [ python ]
#          args:
#            [
#              "-rn", # Only display messages
#              "-sn", # Don't display the score
#            ]

        - id: run tests
          name: run tests
          entry: python -m pytest -v ./tests
          language: system
          always_run: true
          pass_filenames: falsepre-commit hook
