repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
#  - repo: https://github.com/ambv/black
#    rev: stable
#    hooks:
#      - id: black
#      - language_version: python3.9
  - repo: local
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: bash tests/run_pylint.sh
#        language: system

      - id: tests
        name: run tests
        entry: python -m pytest -v ./tests
        language: system
        always_run: true
        pass_filenames: false
#      - id: run_black
#        name: run_black
#        entry: bash tests/run_black.sh
#        language: system
#        always_run: true
#        pass_filenames: false
